version: '3.8'

services:

    nginx:
      container_name: nginx
      restart: always
      image: nginx:1.16.1-alpine
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./data/nginx:/etc/nginx/conf.d
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      ports:
          - 80:80
          - 443:443

    certbot:
      image: certbot/certbot
      volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"